export type Dimension = 'E' | 'I' | 'S' | 'N' | 'T' | 'F' | 'J' | 'P';

export interface Question {
  id: number;
  text: string;
  optionA: string;
  optionB: string;
  dimA: Dimension;
  dimB: Dimension;
}

export const questions: Question[] = [
  { id: 1, text: "When you want to go somewhere for the day, would you rather:", optionA: "Plan what you will do and when", optionB: "Just go without thinking", dimA: 'J', dimB: 'P' },
  { id: 2, text: "If you were a teacher, would you rather teach:", optionA: "Fact-based courses", optionB: "Theory-based courses", dimA: 'S', dimB: 'N' },
  { id: 3, text: "Are you usually:", optionA: "A sociable person", optionB: "A quiet and reserved person", dimA: 'E', dimB: 'I' },
  { id: 4, text: "Do you prefer to:", optionA: "Arrange dates, parties, etc., in advance", optionB: "Be free to do whatever looks like fun when the time comes", dimA: 'J', dimB: 'P' },
  { id: 5, text: "Do you usually get along better with:", optionA: "Realistic people", optionB: "Imaginative people", dimA: 'S', dimB: 'N' },
  { id: 6, text: "When you are with a group of people, would you usually rather:", optionA: "Join in the talk of the group", optionB: "Talk individually with people you know well", dimA: 'E', dimB: 'I' },
  { id: 7, text: "Are you more often:", optionA: "A person of feeling than logic", optionB: "A person of logic than feeling", dimA: 'F', dimB: 'T' },
  { id: 8, text: "Do you prefer to do most things:", optionA: "According to a plan", optionB: "On the spur of the moment", dimA: 'J', dimB: 'P' },
  { id: 9, text: "Would you rather be considered:", optionA: "A practical person", optionB: "An inventive person", dimA: 'S', dimB: 'N' },
  { id: 10, text: "In a large group, do you more often:", optionA: "Introduce others", optionB: "Get introduced", dimA: 'E', dimB: 'I' },
  { id: 11, text: "Does following a schedule:", optionA: "Appeal to you", optionB: "Cramp you", dimA: 'J', dimB: 'P' },
  { id: 12, text: "Do you prefer:", optionA: "Practical people with common sense", optionB: "Flexible and open-minded people", dimA: 'S', dimB: 'N' },
  { id: 13, text: "Do you feel it usually takes others:", optionA: "A short time to get to know you", optionB: "A long time to get to know you", dimA: 'E', dimB: 'I' },
  { id: 14, text: "Is it a higher compliment to be called:", optionA: "A person of real feeling", optionB: "A consistently reasonable person", dimA: 'F', dimB: 'T' },
  { id: 15, text: "When it comes to making plans for the weekend, do you feel it is:", optionA: "Very necessary", optionB: "Unnecessary", dimA: 'J', dimB: 'P' },
  { id: 16, text: "Would you rather have as a friend someone who:", optionA: "Is down-to-earth", optionB: "Always has new ideas", dimA: 'S', dimB: 'N' },
  { id: 17, text: "Most of the time, do you prefer to:", optionA: "Be with others", optionB: "Be alone", dimA: 'E', dimB: 'I' },
  { id: 18, text: "In your daily work, do you like to:", optionA: "Plan and finish your work ahead of time to avoid pressure", optionB: "Work against the clock under pressure", dimA: 'J', dimB: 'P' },
  { id: 19, text: "When reading for pleasure, do you:", optionA: "Like writers to say exactly what they mean", optionB: "Enjoy odd or original ways of saying things", dimA: 'S', dimB: 'N' },
  { id: 20, text: "Can you:", optionA: "Talk easily to almost anyone for as long as you have to", optionB: "Find a lot to say only to certain people or under certain conditions", dimA: 'E', dimB: 'I' },
  { id: 21, text: "Are you more inclined to:", optionA: "Act on feelings", optionB: "Act on logic", dimA: 'F', dimB: 'T' },
  { id: 22, text: "When you have a special job to do, do you like to:", optionA: "Organize it carefully before you start", optionB: "Find out what is necessary as you go along", dimA: 'J', dimB: 'P' },
  { id: 23, text: "When doing something that many other people do, does it appeal to you more to:", optionA: "Do it in the accepted way", optionB: "Invent a way of your own", dimA: 'S', dimB: 'N' },
  { id: 24, text: "Can the new people you meet:", optionA: "Tell what you are interested in right away", optionB: "Only tell after they really get to know you", dimA: 'E', dimB: 'I' },
  { id: 25, text: "In planning a trip, would you prefer to:", optionA: "Know beforehand what you will be doing most days", optionB: "Let the days take care of themselves", dimA: 'J', dimB: 'P' },
  { id: 26, text: "Do most people consider you:", optionA: "Very open and frank", optionB: "Rather private about your own affairs", dimA: 'E', dimB: 'I' },
  { id: 27, text: "Which word appeals to you more:", optionA: "Facts", optionB: "Ideas", dimA: 'S', dimB: 'N' },
  { id: 28, text: "Which word appeals to you more:", optionA: "Warmth", optionB: "Firmness", dimA: 'F', dimB: 'T' },
  { id: 29, text: "Which word appeals to you more:", optionA: "Practical", optionB: "Innovative", dimA: 'S', dimB: 'N' },
  { id: 30, text: "Which word appeals to you more:", optionA: "Planned", optionB: "Spontaneous", dimA: 'J', dimB: 'P' },
  { id: 31, text: "Which word appeals to you more:", optionA: "Concrete", optionB: "Abstract", dimA: 'S', dimB: 'N' },
  { id: 32, text: "Which word appeals to you more:", optionA: "Feeling", optionB: "Thinking", dimA: 'F', dimB: 'T' },
  { id: 33, text: "Which word appeals to you more:", optionA: "Known", optionB: "Novel", dimA: 'S', dimB: 'N' },
  { id: 34, text: "Which word appeals to you more:", optionA: "Emotional", optionB: "Rational", dimA: 'F', dimB: 'T' },
  { id: 35, text: "Which word appeals to you more:", optionA: "Scheduled", optionB: "Unrestricted", dimA: 'J', dimB: 'P' },
  { id: 36, text: "Which word appeals to you more:", optionA: "Enthusiastic", optionB: "Quiet", dimA: 'E', dimB: 'I' },
  { id: 37, text: "Which word appeals to you more:", optionA: "Gentle", optionB: "Hard", dimA: 'F', dimB: 'T' },
  { id: 38, text: "Which word appeals to you more:", optionA: "Statement", optionB: "Concept", dimA: 'S', dimB: 'N' },
  { id: 39, text: "Which word appeals to you more:", optionA: "Compassionate", optionB: "Strong-willed", dimA: 'F', dimB: 'T' },
  { id: 40, text: "Which word appeals to you more:", optionA: "Factual", optionB: "Theoretical", dimA: 'S', dimB: 'N' },
  { id: 41, text: "Which word appeals to you more:", optionA: "Many friends", optionB: "Few friends", dimA: 'E', dimB: 'I' },
  { id: 42, text: "Which word appeals to you more:", optionA: "Systematic", optionB: "Spontaneous", dimA: 'J', dimB: 'P' },
  { id: 43, text: "Which word appeals to you more:", optionA: "Certainty", optionB: "Speculation", dimA: 'S', dimB: 'N' },
  { id: 44, text: "Which word appeals to you more:", optionA: "Forgiving", optionB: "Firm", dimA: 'F', dimB: 'T' },
  { id: 45, text: "Which word appeals to you more:", optionA: "Inevitability", optionB: "Possibility", dimA: 'S', dimB: 'N' },
  { id: 46, text: "Which word appeals to you more:", optionA: "Appeal to emotions", optionB: "Appeal to reason", dimA: 'F', dimB: 'T' },
  { id: 47, text: "Which word appeals to you more:", optionA: "Talkative", optionB: "Reserved", dimA: 'E', dimB: 'I' },
  { id: 48, text: "Which word appeals to you more:", optionA: "Gentle", optionB: "Strength", dimA: 'F', dimB: 'T' },
  { id: 49, text: "Which word appeals to you more:", optionA: "Reality", optionB: "Ideal", dimA: 'S', dimB: 'N' },
  { id: 50, text: "Which word appeals to you more:", optionA: "Kind-hearted", optionB: "Competent", dimA: 'F', dimB: 'T' },
  { id: 51, text: "Which word appeals to you more:", optionA: "Fact", optionB: "Theory", dimA: 'S', dimB: 'N' },
  { id: 52, text: "Which word appeals to you more:", optionA: "Systematic", optionB: "Random", dimA: 'J', dimB: 'P' },
  { id: 53, text: "Which word appeals to you more:", optionA: "Realistic", optionB: "Imaginative", dimA: 'S', dimB: 'N' },
  { id: 54, text: "Which word appeals to you more:", optionA: "Emotional", optionB: "Objective", dimA: 'F', dimB: 'T' },
  { id: 55, text: "Which word appeals to you more:", optionA: "Build", optionB: "Invent", dimA: 'S', dimB: 'N' },
  { id: 56, text: "Which word appeals to you more:", optionA: "Affectionate", optionB: "Pragmatic", dimA: 'F', dimB: 'T' },
  { id: 57, text: "Which word appeals to you more:", optionA: "Orderly", optionB: "Casual", dimA: 'J', dimB: 'P' },
  { id: 58, text: "Which word appeals to you more:", optionA: "Outgoing", optionB: "Quiet", dimA: 'E', dimB: 'I' },
  { id: 59, text: "Which word appeals to you more:", optionA: "Agree", optionB: "Analyze", dimA: 'F', dimB: 'T' },
  { id: 60, text: "Which word appeals to you more:", optionA: "Factual", optionB: "Imaginative", dimA: 'S', dimB: 'N' },
  { id: 61, text: "Which word appeals to you more:", optionA: "Blessing", optionB: "Benefit", dimA: 'F', dimB: 'T' },
  { id: 62, text: "Which word appeals to you more:", optionA: "Detailed", optionB: "General", dimA: 'S', dimB: 'N' },
  { id: 63, text: "Which word appeals to you more:", optionA: "Decision", optionB: "Impulse", dimA: 'J', dimB: 'P' },
  { id: 64, text: "Which word appeals to you more:", optionA: "Make", optionB: "Create", dimA: 'S', dimB: 'N' },
  { id: 65, text: "Which word appeals to you more:", optionA: "Warm", optionB: "Objective", dimA: 'F', dimB: 'T' },
  { id: 66, text: "Which word appeals to you more:", optionA: "Practical", optionB: "Fascinating", dimA: 'S', dimB: 'N' },
  { id: 67, text: "Which word appeals to you more:", optionA: "Considerate", optionB: "Fair", dimA: 'F', dimB: 'T' },
  { id: 68, text: "Which word appeals to you more:", optionA: "Sociable", optionB: "Quiet", dimA: 'E', dimB: 'I' },
  { id: 69, text: "Which word appeals to you more:", optionA: "Sensitive", optionB: "Reasonable", dimA: 'F', dimB: 'T' },
  { id: 70, text: "Which word appeals to you more:", optionA: "Manufacture", optionB: "Design", dimA: 'S', dimB: 'N' },
  { id: 71, text: "Which word appeals to you more:", optionA: "Sympathetic", optionB: "Logical", dimA: 'F', dimB: 'T' },
  { id: 72, text: "Which word appeals to you more:", optionA: "Public", optionB: "Private", dimA: 'E', dimB: 'I' },
  { id: 73, text: "Which word appeals to you more:", optionA: "Compassion", optionB: "Foresight", dimA: 'F', dimB: 'T' },
  { id: 74, text: "Do you usually prefer to:", optionA: "Arrange your leisure activities in advance", optionB: "Do things on the spur of the moment", dimA: 'J', dimB: 'P' },
  { id: 75, text: "Do you find being around a lot of people:", optionA: "Energizes you", optionB: "Often drains you", dimA: 'E', dimB: 'I' },
  { id: 76, text: "In most cases, do you prefer to:", optionA: "Follow a schedule", optionB: "Go with the flow", dimA: 'J', dimB: 'P' },
  { id: 77, text: "At parties, do you:", optionA: "Always have fun", optionB: "Sometimes get bored", dimA: 'E', dimB: 'I' },
  { id: 78, text: "When making a decision, is it more important to you to:", optionA: "Consider people's feelings and opinions", optionB: "Weigh the facts", dimA: 'F', dimB: 'T' },
  { id: 79, text: "Do you like to:", optionA: "Prepare well in advance", optionB: "See how things develop before making a plan", dimA: 'J', dimB: 'P' },
  { id: 80, text: "Is it:", optionA: "Easy for others to get to know you", optionB: "Hard for others to get to know you", dimA: 'E', dimB: 'I' },
  { id: 81, text: "Do you prefer to:", optionA: "Stick to methods that already work", optionB: "Analyze what is still wrong and challenge unsolved problems", dimA: 'S', dimB: 'N' },
  { id: 82, text: "Do you feel you are more of:", optionA: "An organized person", optionB: "A spontaneous person", dimA: 'J', dimB: 'P' },
  { id: 83, text: "Can you:", optionA: "Talk endlessly with almost anyone if you want to", optionB: "Only talk at length with people who share your interests", dimA: 'E', dimB: 'I' },
  { id: 84, text: "Would you rather work under a boss who is:", optionA: "Good-natured but inconsistent", optionB: "Strict but organized", dimA: 'F', dimB: 'T' },
  { id: 85, text: "Do you prefer to do most things according to:", optionA: "A set schedule", optionB: "How you feel that day", dimA: 'J', dimB: 'P' },
  { id: 86, text: "At a party, do you:", optionA: "Do most of the talking", optionB: "Do most of the listening", dimA: 'E', dimB: 'I' },
  { id: 87, text: "Usually, do you prefer courses that involve:", optionA: "Concrete content", optionB: "Concepts and principles", dimA: 'S', dimB: 'N' },
  { id: 88, text: "When starting a big project due in a week, do you:", optionA: "Take time to list the things to do and their order", optionB: "Dive right in", dimA: 'J', dimB: 'P' },
  { id: 89, text: "In social situations, do you usually find it:", optionA: "Easy to talk to most people for a long time", optionB: "Hard to start and maintain long conversations with some people", dimA: 'E', dimB: 'I' },
  { id: 90, text: "Is it a higher compliment to be called:", optionA: "Compassionate", optionB: "Competitive", dimA: 'F', dimB: 'T' },
  { id: 91, text: "Do you feel that following a plan is:", optionA: "Helpful and appropriate most of the time", optionB: "Sometimes necessary, but annoying", dimA: 'J', dimB: 'P' },
  { id: 92, text: "Do you usually:", optionA: "Mingle well with others", optionB: "Tend to keep to yourself", dimA: 'E', dimB: 'I' },
  { id: 93, text: "In general, to complete a major task, do you tend to:", optionA: "Define every step before starting", optionB: "Figure out what needs to be done as you go", dimA: 'J', dimB: 'P' }
];

export const personalityDescriptions: Record<string, { title: string, desc: string }> = {
  "ISTJ": { title: "The Inspector", desc: "Quiet, serious, earn success by thoroughness and dependability. Practical, matter-of-fact, realistic, and responsible. Decide logically what should be done and work toward it steadily, regardless of distractions. Take pleasure in making everything orderly and organized - their work, their home, their life. Value traditions and loyalty." },
  "ISFJ": { title: "The Protector", desc: "Quiet, friendly, responsible, and conscientious. Committed and steady in meeting their obligations. Thorough, painstaking, and accurate. Loyal, considerate, notice and remember specifics about people who are important to them, concerned with how others feel. Strive to create an orderly and harmonious environment at work and at home." },
  "INFJ": { title: "The Counselor", desc: "Seek meaning and connection in ideas, relationships, and material possessions. Want to understand what motivates people and are insightful about others. Conscientious and committed to their firm values. Develop a clear vision about how best to serve the common good. Organized and decisive in implementing their vision." },
  "INTJ": { title: "The Mastermind", desc: "Have original minds and great drive for implementing their ideas and achieving their goals. Quickly see patterns in external events and develop long-range explanatory perspectives. When committed, organize a job and carry it through. Skeptical and independent, have high standards of competence and performance - for themselves and others." },
  "ISTP": { title: "The Crafter", desc: "Tolerant and flexible; quiet observers until a problem appears, then act quickly to find workable solutions. Analyze what makes things work and readily get through large amounts of data to isolate the core of practical problems. Interested in cause and effect, organize facts using logical principles, value efficiency." },
  "ISFP": { title: "The Composer", desc: "Quiet, friendly, sensitive, and kind. Enjoy the present moment, what's going on around them. Like to have their own space and to work within their own time frame. Loyal and committed to their values and to people who are important to them. Dislike disagreements and conflicts, do not force their opinions or values on others." },
  "INFP": { title: "The Healer", desc: "Idealistic, loyal to their values and to people who are important to them. Want an external life that is congruent with their values. Curious, quick to see possibilities, can be catalysts for implementing ideas. Seek to understand people and to help them fulfill their potential. Adaptable, flexible, and accepting unless a value is threatened." },
  "INTP": { title: "The Architect", desc: "Seek to develop logical explanations for everything that interests them. Theoretical and abstract, interested more in ideas than in social interaction. Quiet, contained, flexible, and adaptable. Have unusual ability to focus in depth to solve problems in their area of interest. Skeptical, sometimes critical, always analytical." },
  "ESTP": { title: "The Promoter", desc: "Flexible and tolerant, they take a pragmatic approach focused on immediate results. Theories and conceptual explanations bore them - they want to act energetically to solve the problem. Focus on the here-and-now, spontaneous, enjoy each moment that they can be active with others. Enjoy material comforts and style. Learn best through doing." },
  "ESFP": { title: "The Performer", desc: "Outgoing, friendly, and accepting. Exuberant lovers of life, people, and material comforts. Enjoy working with others to make things happen. Bring common sense and a realistic approach to their work, and make work fun. Flexible and spontaneous, adapt readily to new people and environments. Learn best by trying a new skill with other people." },
  "ENFP": { title: "The Champion", desc: "Warmly enthusiastic and imaginative. See life as full of possibilities. Make connections between events and information very quickly, and confidently proceed based on the patterns they see. Want a lot of affirmation from others, and readily give appreciation and support. Spontaneous and flexible, often rely on their ability to improvise and their verbal fluency." },
  "ENTP": { title: "The Inventor", desc: "Quick, ingenious, stimulating, alert, and outspoken. Resourceful in solving new and challenging problems. Adept at generating conceptual possibilities and then analyzing them strategically. Good at reading other people. Bored by routine, will seldom do the same thing the same way, apt to turn to one new interest after another." },
  "ESTJ": { title: "The Supervisor", desc: "Practical, realistic, matter-of-fact. Decisive, quickly move to implement decisions. Organize projects and people to get things done, focus on getting results in the most efficient way possible. Take care of routine details. Have a clear set of logical standards, systematically follow them and want others to also. Forceful in implementing their plans." },
  "ESFJ": { title: "The Provider", desc: "Warmhearted, conscientious, and cooperative. Want harmony in their environment, work with determination to establish it. Like to work with others to complete tasks accurately and on time. Loyal, follow through even in small matters. Notice what others need in their day-by-day lives and try to provide it. Want to be appreciated for who they are and for what they contribute." },
  "ENFJ": { title: "The Teacher", desc: "Warm, empathetic, responsive, and responsible. Highly attuned to the emotions, needs, and motivations of others. Find potential in everyone, want to help others fulfill their potential. May act as catalysts for individual and group growth. Loyal, responsive to praise and criticism. Sociable, facilitate others in a group, and provide inspiring leadership." },
  "ENTJ": { title: "The Fieldmarshal", desc: "Frank, decisive, assume leadership readily. Quickly see illogical and inefficient procedures and policies, develop and implement comprehensive systems to solve organizational problems. Enjoy long-term planning and goal setting. Usually well informed, well read, enjoy expanding their knowledge and passing it on to others. Forceful in presenting their ideas." }
};
