export type Dimension = 'E' | 'I' | 'S' | 'N' | 'T' | 'F' | 'J' | 'P';

export interface Question {
  id: number;
  text: string;
  optionA: string;
  optionB: string;
  dimA: Dimension;
  dimB: Dimension;
}

export const questions: Question[] = [
  { id: 1, text: "當你某日想去某個地方，你會______？", optionA: "計畫好將做的事情以及何時做", optionB: "什麼都不想就去", dimA: 'J', dimB: 'P' },
  { id: 2, text: "如果你是一位老師，你願教______？", optionA: "涉及事實的課程", optionB: "涉及理論的課程", dimA: 'S', dimB: 'N' },
  { id: 3, text: "你通常是______？", optionA: "一個善於交際的人", optionB: "安靜緘默的人", dimA: 'E', dimB: 'I' },
  { id: 4, text: "你喜歡______？", optionA: "事先安排好約會，聚會等", optionB: "只要時機恰當就無拘無束地做任何有趣的事", dimA: 'J', dimB: 'P' },
  { id: 5, text: "你通常和______相處得更好？", optionA: "現實的人", optionB: "想像力豐富的人", dimA: 'S', dimB: 'N' },
  { id: 6, text: "當你和一群人在一起時，你會______？", optionA: "參加大家的談話", optionB: "只同你熟知的人單獨談話", dimA: 'E', dimB: 'I' },
  { id: 7, text: "往往，你是______？", optionA: "情感駕馭理智", optionB: "理智駕馭情感", dimA: 'F', dimB: 'T' },
  { id: 8, text: "你更喜歡______做多數事情？", optionA: "有計畫地", optionB: "即興時", dimA: 'J', dimB: 'P' },
  { id: 9, text: "你願意自己被認為是一個______？", optionA: "善於動手的人", optionB: "善於創意的人", dimA: 'S', dimB: 'N' },
  { id: 10, text: "在大群體中，你常更多地______？", optionA: "介紹他人", optionB: "由別人來介紹你", dimA: 'E', dimB: 'I' },
  { id: 11, text: "按日程表辦事______？", optionA: "正合你意", optionB: "束縛了你", dimA: 'J', dimB: 'P' },
  { id: 12, text: "你更喜歡______？", optionA: "務實且有豐富常識的人", optionB: "頭腦靈活的人", dimA: 'S', dimB: 'N' },
  { id: 13, text: "你覺得通常別人要花費______？", optionA: "一小段時間來了解你", optionB: "很久來了解你", dimA: 'E', dimB: 'I' },
  { id: 14, text: "被稱為______是更高的讚賞？", optionA: "感性的人", optionB: "一貫理性的人", dimA: 'F', dimB: 'T' },
  { id: 15, text: "對於制定週末計畫，你覺得______？", optionA: "很有必要", optionB: "沒必要", dimA: 'J', dimB: 'P' },
  { id: 16, text: "你願把______作為朋友？", optionA: "腳踏實地的人", optionB: "常有新觀點的人", dimA: 'S', dimB: 'N' },
  { id: 17, text: "多數時候，你傾向於______？", optionA: "同他人在一起", optionB: "獨處", dimA: 'E', dimB: 'I' },
  { id: 18, text: "日常工作中，你喜歡______？", optionA: "通常先安排好工作並加以完成，以免壓力過大", optionB: "在時間緊迫的情況下爭分奪秒地工作", dimA: 'J', dimB: 'P' },
  { id: 19, text: "當你為了消遣而閱讀時，你______？", optionA: "喜歡作者確切地表達其意思", optionB: "欣賞奇特新穎的表達方式", dimA: 'S', dimB: 'N' },
  { id: 20, text: "你能否______？", optionA: "只要願意就能輕鬆地同幾乎任何人說個沒完", optionB: "只能在特定場合下或同特定的人才願意講許多話", dimA: 'E', dimB: 'I' },
  { id: 21, text: "你更傾向於______？", optionA: "感性地做事", optionB: "依邏輯行事", dimA: 'F', dimB: 'T' },
  { id: 22, text: "當有一項特殊工作時，你會______？", optionA: "在開始前精心組織策劃", optionB: "在工作進行中找出必要環節", dimA: 'J', dimB: 'P' },
  { id: 23, text: "做很多人都會做的事情時，你喜歡______？", optionA: "按慣例做", optionB: "按自己獨創的方式做", dimA: 'S', dimB: 'N' },
  { id: 24, text: "你新認識的人______說出你的興趣所在？", optionA: "馬上就能", optionB: "只有當他們真正了解你之後才能", dimA: 'E', dimB: 'I' },
  { id: 25, text: "在計畫一次旅行時，你更喜歡______？", optionA: "事先就知道在大部分日子所將做的事情", optionB: "在多數情況下隨心所欲地行事", dimA: 'J', dimB: 'P' },
  { id: 26, text: "多數人認為你______？", optionA: "非常坦率", optionB: "不太把自己的事情告訴別人", dimA: 'E', dimB: 'I' },
  { id: 27, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "事實", optionB: "觀點", dimA: 'S', dimB: 'N' },
  { id: 28, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "熱忱", optionB: "堅決", dimA: 'F', dimB: 'T' },
  { id: 29, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "切實", optionB: "創新", dimA: 'S', dimB: 'N' },
  { id: 30, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "有計畫", optionB: "隨意", dimA: 'J', dimB: 'P' },
  { id: 31, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "實在", optionB: "抽象", dimA: 'S', dimB: 'N' },
  { id: 32, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "感覺", optionB: "思考", dimA: 'F', dimB: 'T' },
  { id: 33, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "已知的", optionB: "新穎的", dimA: 'S', dimB: 'N' },
  { id: 34, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "感性", optionB: "理性", dimA: 'F', dimB: 'T' },
  { id: 35, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "安排好的", optionB: "不受限制的", dimA: 'J', dimB: 'P' },
  { id: 36, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "熱情", optionB: "安靜", dimA: 'E', dimB: 'I' },
  { id: 37, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "溫柔", optionB: "堅硬", dimA: 'F', dimB: 'T' },
  { id: 38, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "陳述", optionB: "觀念", dimA: 'S', dimB: 'N' },
  { id: 39, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "慈悲心腸", optionB: "意志堅強", dimA: 'F', dimB: 'T' },
  { id: 40, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "事實的", optionB: "理論的", dimA: 'S', dimB: 'N' },
  { id: 41, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "很多朋友", optionB: "少許朋友", dimA: 'E', dimB: 'I' },
  { id: 42, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "系統的", optionB: "自發的", dimA: 'J', dimB: 'P' },
  { id: 43, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "確定", optionB: "推測", dimA: 'S', dimB: 'N' },
  { id: 44, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "寬容", optionB: "堅定", dimA: 'F', dimB: 'T' },
  { id: 45, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "必然性", optionB: "可能性", dimA: 'S', dimB: 'N' },
  { id: 46, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "動之以情", optionB: "曉之以理", dimA: 'F', dimB: 'T' },
  { id: 47, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "健談", optionB: "緘默", dimA: 'E', dimB: 'I' },
  { id: 48, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "溫和", optionB: "力量", dimA: 'F', dimB: 'T' },
  { id: 49, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "現實", optionB: "理想", dimA: 'S', dimB: 'N' },
  { id: 50, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "好心的", optionB: "稱職的", dimA: 'F', dimB: 'T' },
  { id: 51, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "事實", optionB: "理論", dimA: 'S', dimB: 'N' },
  { id: 52, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "系統", optionB: "隨機", dimA: 'J', dimB: 'P' },
  { id: 53, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "現實的", optionB: "想像的", dimA: 'S', dimB: 'N' },
  { id: 54, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "易動情的", optionB: "客觀的", dimA: 'F', dimB: 'T' },
  { id: 55, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "建造", optionB: "發明", dimA: 'S', dimB: 'N' },
  { id: 56, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "感情豐富的", optionB: "注重實際的", dimA: 'F', dimB: 'T' },
  { id: 57, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "有序的", optionB: "隨便的", dimA: 'J', dimB: 'P' },
  { id: 58, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "開朗", optionB: "文靜", dimA: 'E', dimB: 'I' },
  { id: 59, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "認同", optionB: "分析", dimA: 'F', dimB: 'T' },
  { id: 60, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "事實的", optionB: "想像的", dimA: 'S', dimB: 'N' },
  { id: 61, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "祝福", optionB: "利益", dimA: 'F', dimB: 'T' },
  { id: 62, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "詳實", optionB: "概括", dimA: 'S', dimB: 'N' },
  { id: 63, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "決定", optionB: "衝動", dimA: 'J', dimB: 'P' },
  { id: 64, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "製作", optionB: "創造", dimA: 'S', dimB: 'N' },
  { id: 65, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "熱情", optionB: "客觀", dimA: 'F', dimB: 'T' },
  { id: 66, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "實用的", optionB: "迷人的", dimA: 'S', dimB: 'N' },
  { id: 67, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "體諒的", optionB: "公正的", dimA: 'F', dimB: 'T' },
  { id: 68, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "愛交際", optionB: "愛文靜", dimA: 'E', dimB: 'I' },
  { id: 69, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "敏感", optionB: "合理", dimA: 'F', dimB: 'T' },
  { id: 70, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "製造", optionB: "設計", dimA: 'S', dimB: 'N' },
  { id: 71, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "有同情心", optionB: "有邏輯頭腦", dimA: 'F', dimB: 'T' },
  { id: 72, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "公開的", optionB: "私人的", dimA: 'E', dimB: 'I' },
  { id: 73, text: "在以下各對詞中，你更傾向於哪一個：", optionA: "同情憐憫", optionB: "深謀遠慮", dimA: 'F', dimB: 'T' },
  { id: 74, text: "通常你更喜歡______？", optionA: "提前安排好業餘活動", optionB: "即興地做事情", dimA: 'J', dimB: 'P' },
  { id: 75, text: "你覺得被許多人圍著______？", optionA: "讓你感到更有精神", optionB: "常讓你精力衰竭", dimA: 'E', dimB: 'I' },
  { id: 76, text: "多數情況下，你更喜歡______？", optionA: "按日程表辦事", optionB: "順其自然", dimA: 'J', dimB: 'P' },
  { id: 77, text: "在聚會中，你______？", optionA: "總是玩得很開心", optionB: "有時覺得無趣", dimA: 'E', dimB: 'I' },
  { id: 78, text: "作決定時，對於你來說更重要的是______？", optionA: "考慮人們的感受和觀點", optionB: "權衡事實", dimA: 'F', dimB: 'T' },
  { id: 79, text: "你喜歡______？", optionA: "事先很早就作好準備", optionB: "看清事態如何發展再作計畫", dimA: 'J', dimB: 'P' },
  { id: 80, text: "別人______了解你？", optionA: "很容易", optionB: "很難", dimA: 'E', dimB: 'I' },
  { id: 81, text: "你喜歡的處事方式是______？", optionA: "堅持那些已經有效的方法", optionB: "分析哪些仍有錯並挑戰未解決的問題", dimA: 'S', dimB: 'N' },
  { id: 82, text: "你覺得自己更偏向於是一個______？", optionA: "有組織性的人", optionB: "自發性的人", dimA: 'J', dimB: 'P' },
  { id: 83, text: "你______？", optionA: "只要願意，就能和幾乎任何一個人談個沒完", optionB: "只同和自己有共同興趣的人才能長時間的交談", dimA: 'E', dimB: 'I' },
  { id: 84, text: "你願在一個______老闆（老師）手下工作（學習）？", optionA: "脾氣好，但前後不一致", optionB: "對人嚴厲，但有條理", dimA: 'F', dimB: 'T' },
  { id: 85, text: "你更喜歡按照______做大多數事情？", optionA: "已定的日程表", optionB: "當天的感覺", dimA: 'J', dimB: 'P' },
  { id: 86, text: "在聚會中，你______？", optionA: "自己聊得多", optionB: "聽別人聊得多", dimA: 'E', dimB: 'I' },
  { id: 87, text: "通常，你更喜歡上涉及______的課程？", optionA: "具體內容", optionB: "概念和原則", dimA: 'S', dimB: 'N' },
  { id: 88, text: "當你開始了一項必須在一週內完成的大項目時，你會______？", optionA: "花時間列出所要做的事情及其先後次序", optionB: "直接開始", dimA: 'J', dimB: 'P' },
  { id: 89, text: "在社交場合中，你通常覺得______？", optionA: "很容易同大多數人長時間談話", optionB: "同某些人很難開展和維持長時間的談話", dimA: 'E', dimB: 'I' },
  { id: 90, text: "被稱為______是更高的讚賞？", optionA: "富有同情心", optionB: "有競爭力", dimA: 'F', dimB: 'T' },
  { id: 91, text: "你覺得按計畫行事______？", optionA: "多數時候是有幫助的、適宜的", optionB: "有時必要，便令人不爽", dimA: 'J', dimB: 'P' },
  { id: 92, text: "你通常______？", optionA: "同大家打成一片", optionB: "傾向於獨處", dimA: 'E', dimB: 'I' },
  { id: 93, text: "總的來說，要完成一項重大任務，你傾向於______？", optionA: "開始先確定每一個步驟", optionB: "邊做邊考慮必須完成的事", dimA: 'J', dimB: 'P' }
];

export const personalityDescriptions: Record<string, { title: string, desc: string }> = {
  "ISTJ": { title: "檢查員型", desc: "安靜、嚴肅，透過全面性和可靠性獲得成功。實際，有責任感。決定有邏輯性，並一步步地朝著目標前進，不易分心。喜歡將工作、家庭和生活都安排得井井有條。重視傳統和忠誠。" },
  "ISFJ": { title: "照顧者型", desc: "安靜、友好、有責任感和良知。堅定地致力於完成他們的義務。全面、勤勉、精確，忠誠、體貼，留心和記得他們重視的人的小細節，關心他們的感受。努力把工作和家庭環境營造得有序而溫馨。" },
  "INFJ": { title: "博愛型", desc: "尋求思想、關係、物質等之間的意義和聯繫。希望了解什麼能夠激勵人，對人有很強的洞察力。有責任心，堅持自己的價值觀。對於怎樣更好的服務大眾有清晰的遠景。在對於目標的實現過程中有計畫而且果斷堅定。" },
  "INTJ": { title: "專家型", desc: "在實現自己的想法和達成自己的目標時有創新的想法和非凡的動力。能很快洞察到外界事物間的規律並形成長期的遠景計畫。一旦決定做一件事就會開始規劃並直到完成為止。多疑、獨立，對於自己和他人能力和表現的要求都非常高。" },
  "ISTP": { title: "冒險家型", desc: "靈活、忍耐力強，是個安靜的觀察者直到有問題發生，就會馬上行動，找到實用的解決方法。分析事物運作的原理，能從大量的資訊中很快的找到關鍵的癥結所在。對於原因和結果感興趣，用邏輯的方式處理問題，重視效率。" },
  "ISFP": { title: "藝術家型", desc: "安靜、友好、敏感、和善。享受當前。喜歡有自己的空間，喜歡能按照自己的時間表工作。對於自己的價值觀和自己覺得重要的人非常忠誠，有責任心。不喜歡爭論和衝突。不會將自己的觀念和價值觀強加到別人身上。" },
  "INFP": { title: "哲學家型", desc: "理想主義，對於自己的價值觀和自己覺得重要的人非常忠誠。希望外部的生活和自己內心的價值觀是統一的。好奇心重，很快能看到事情的可能性，能成為實現想法的催化劑。尋求理解別人和幫助他們實現潛能。適應力強，靈活，善於接受，除非是有悖於自己的價值觀的。" },
  "INTP": { title: "學者型", desc: "對於自己感興趣的任何事物都尋求找到合理的解釋。喜歡理論性的和抽象的事物，熱衷於思考而非社交活動。安靜、內向、靈活、適應力強。對於自己感興趣的領域有超凡的集中精力深度解決問題的能力。多疑，有時會有點挑剔，喜歡分析。" },
  "ESTP": { title: "挑戰者型", desc: "靈活、忍耐力強，實際，注重結果。覺得理論和抽象的解釋非常無趣。喜歡積極地採取行動解決問題。注重當前，自然不做作，享受和他人在一起的時刻。喜歡物質享受和時尚。學習新事物最有效的方式是透過親身感受和練習。" },
  "ESFP": { title: "表演者型", desc: "外向、友好、接受力強。熱愛生活、人類和物質上的享受。喜歡和別人一起將事情做成功。在工作中講究常識和實用性，並使工作顯得有趣。靈活、自然不做作，對於新的任何事物都能很快地適應。學習新事物最有效的方式是和他人一起嘗試。" },
  "ENFP": { title: "公關型", desc: "熱情洋溢、富有想像力。認為人生有很多的可能性。能很快地將事情和資訊聯繫起來，然後很自信地根據自己的判斷解決問題。總是需要得到別人的認可，也總是準備著給與他人賞識和幫助。靈活、自然不做作，有很強的即興發揮的能力，言語流暢。" },
  "ENTP": { title: "智多星型", desc: "反應快、睿智，有激勵別人的能力，警覺性強、直言不諱。在解決新的、具有挑戰性的問題時機智而有策略。善於找出理論上的可能性，然後再用戰略的眼光分析。善於理解別人。不喜歡例行公事，很少會用相同的方法做相同的事情，傾向於一個接一個的發展新的愛好。" },
  "ESTJ": { title: "管家型", desc: "實際、現實主義。果斷，一旦下決心就會馬上行動。善於將項目和人組織起來將事情完成，並盡可能用最有效率的方法得到結果。注重日常的細節。有一套非常清晰的邏輯標準，有系統性地遵循，並希望他人也同樣遵循。在實施計畫時強而有力。" },
  "ESFJ": { title: "主人型", desc: "熱心腸、有責任心、合作。希望周邊的環境溫馨而和諧，並為此果斷地執行。喜歡和他人一起精確並及時地完成任務。事無鉅細都會保持忠誠。能體察到他人在日常生活中的所需並竭盡全力幫助。希望自己和自己的所為能受到他人的認可和賞識。" },
  "ENFJ": { title: "教導型", desc: "熱情、為他人著想、易感應、有責任心。非常注重他人的感情、需求和動機。善於發現他人的潛能，並希望能幫助他們實現。能成為個人或群體成長和進步的催化劑。忠誠，對於讚揚和批評都會積極地回應。友善、好社交。在團體中能很好地幫助他人，並有鼓舞他人的領導能力。" },
  "ENTJ": { title: "統帥型", desc: "坦誠、果斷，有天生的領導能力。能很快看到公司/組織程序和政策中的不合理性和低效能性，發展並實施有效和全面的系統來解決問題。善於做長期的計畫和目標的設定。通常見多識廣，博覽群書，喜歡拓廣自己的知識面並將此分享給他人。在陳述自己的想法時非常強而有力。" }
};
