export type Dimension = 'E' | 'I' | 'S' | 'N' | 'T' | 'F' | 'J' | 'P';

export interface Question {
  id: number;
  text: string;
  optionA: string;
  optionB: string;
  dimA: Dimension;
  dimB: Dimension;
}

export const questions: Question[] = [
  { id: 1, text: "當你打算外出一天時，你傾向於：", optionA: "事先計畫好要做什麼、什麼時間做", optionB: "什麼都不想直接出發", dimA: 'J', dimB: 'P' },
  { id: 2, text: "如果你是一名教師，你寧願教：", optionA: "以事實為主的課程", optionB: "以理論為主的課程", dimA: 'S', dimB: 'N' },
  { id: 3, text: "你通常是：", optionA: "一個善於交際的人", optionB: "一個安靜、內向的人", dimA: 'E', dimB: 'I' },
  { id: 4, text: "你更喜歡：", optionA: "提前安排好約會、派對等活動", optionB: "到時候想做什麼就做什麼，隨性而為", dimA: 'J', dimB: 'P' },
  { id: 5, text: "你通常與哪種人相處得更好：", optionA: "現實的人", optionB: "富有想像力的人", dimA: 'S', dimB: 'N' },
  { id: 6, text: "當你在一群人當中時，你通常會：", optionA: "加入大家的談話", optionB: "單獨與熟悉的人交談", dimA: 'E', dimB: 'I' },
  { id: 7, text: "你通常是：", optionA: "感性重於理性的人", optionB: "理性重於感性的人", dimA: 'F', dimB: 'T' },
  { id: 8, text: "你喜歡做大多數事情：", optionA: "按照計畫進行", optionB: "心血來潮，隨性而為", dimA: 'J', dimB: 'P' },
  { id: 9, text: "你更希望被認為是：", optionA: "一個務實的人", optionB: "一個有創意的人", dimA: 'S', dimB: 'N' },
  { id: 10, text: "在大群體中，你通常會：", optionA: "主動介紹別人", optionB: "等著被介紹", dimA: 'E', dimB: 'I' },
  { id: 11, text: "遵守預定的時間表：", optionA: "讓你感到自在", optionB: "讓你感到受限", dimA: 'J', dimB: 'P' },
  { id: 12, text: "你更喜歡：", optionA: "有常識、務實的人", optionB: "靈活、思想開放的人", dimA: 'S', dimB: 'N' },
  { id: 13, text: "你覺得別人通常需要：", optionA: "很短的時間就能了解你", optionB: "很長的時間才能了解你", dimA: 'E', dimB: 'I' },
  { id: 14, text: "對你來說，哪種稱讚更高級：", optionA: "一個真正感性的人", optionB: "一個始終理性的人", dimA: 'F', dimB: 'T' },
  { id: 15, text: "談到週末計畫，你覺得：", optionA: "非常有必要", optionB: "沒必要", dimA: 'J', dimB: 'P' },
  { id: 16, text: "你更希望朋友是：", optionA: "腳踏實地的人", optionB: "總是充滿新點子的人", dimA: 'S', dimB: 'N' },
  { id: 17, text: "大多數時候，你更喜歡：", optionA: "和別人在一起", optionB: "獨處", dimA: 'E', dimB: 'I' },
  { id: 18, text: "在日常工作中，你喜歡：", optionA: "提前計畫並完成工作以避免壓力", optionB: "在壓力下與時間賽跑", dimA: 'J', dimB: 'P' },
  { id: 19, text: "閱讀消遣時，你：", optionA: "喜歡作者準確表達其原意", optionB: "喜歡奇特或獨創的表達方式", dimA: 'S', dimB: 'N' },
  { id: 20, text: "你能：", optionA: "輕鬆地與幾乎任何人交談很久", optionB: "只對某些人或在某些情況下才有話說", dimA: 'E', dimB: 'I' },
  { id: 21, text: "你更傾向於：", optionA: "憑感情行事", optionB: "憑邏輯行事", dimA: 'F', dimB: 'T' },
  { id: 22, text: "當你有一項特殊任務時，你喜歡：", optionA: "在開始前仔細組織計畫", optionB: "在進行過程中隨機應變", dimA: 'J', dimB: 'P' },
  { id: 23, text: "做大家都在做的事情時，你更感興趣：", optionA: "按大家公認的方式去做", optionB: "發明自己的方式去做", dimA: 'S', dimB: 'N' },
  { id: 24, text: "剛認識你的人：", optionA: "能馬上看出你的興趣所在", optionB: "只有在真正了解你之後才能看出", dimA: 'E', dimB: 'I' },
  { id: 25, text: "在計畫旅行時，你更喜歡：", optionA: "預先知道大部分時間會做什麼", optionB: "隨遇而安，看情況決定", dimA: 'J', dimB: 'P' },
  { id: 26, text: "大多數人認為你：", optionA: "非常開朗坦率", optionB: "對私人事務相當保密", dimA: 'E', dimB: 'I' },
  { id: 27, text: "哪個詞更吸引你：", optionA: "事實", optionB: "想法", dimA: 'S', dimB: 'N' },
  { id: 28, text: "哪個詞更吸引你：", optionA: "熱忱", optionB: "堅定", dimA: 'F', dimB: 'T' },
  { id: 29, text: "哪個詞更吸引你：", optionA: "務實", optionB: "創新", dimA: 'S', dimB: 'N' },
  { id: 30, text: "哪個詞更吸引你：", optionA: "計畫", optionB: "自發", dimA: 'J', dimB: 'P' },
  { id: 31, text: "哪個詞更吸引你：", optionA: "具體", optionB: "抽象", dimA: 'S', dimB: 'N' },
  { id: 32, text: "哪個詞更吸引你：", optionA: "情感", optionB: "思考", dimA: 'F', dimB: 'T' },
  { id: 33, text: "哪個詞更吸引你：", optionA: "已知", optionB: "新穎", dimA: 'S', dimB: 'N' },
  { id: 34, text: "哪個詞更吸引你：", optionA: "感情的", optionB: "理智的", dimA: 'F', dimB: 'T' },
  { id: 35, text: "哪個詞更吸引你：", optionA: "準時", optionB: "不受限", dimA: 'J', dimB: 'P' },
  { id: 36, text: "哪個詞更吸引你：", optionA: "熱情", optionB: "文靜", dimA: 'E', dimB: 'I' },
  { id: 37, text: "哪個詞更吸引你：", optionA: "溫柔", optionB: "強硬", dimA: 'F', dimB: 'T' },
  { id: 38, text: "哪個詞更吸引你：", optionA: "陳述", optionB: "概念", dimA: 'S', dimB: 'N' },
  { id: 39, text: "哪個詞更吸引你：", optionA: "同情心", optionB: "意志堅定", dimA: 'F', dimB: 'T' },
  { id: 40, text: "哪個詞更吸引你：", optionA: "實事求是", optionB: "理論性", dimA: 'S', dimB: 'N' },
  { id: 41, text: "哪個詞更吸引你：", optionA: "許多朋友", optionB: "少數朋友", dimA: 'E', dimB: 'I' },
  { id: 42, text: "哪個詞更吸引你：", optionA: "系統化", optionB: "自發性", dimA: 'J', dimB: 'P' },
  { id: 43, text: "哪個詞更吸引你：", optionA: "確定性", optionB: "推測性", dimA: 'S', dimB: 'N' },
  { id: 44, text: "哪個詞更吸引你：", optionA: "寬容", optionB: "堅定", dimA: 'F', dimB: 'T' },
  { id: 45, text: "哪個詞更吸引你：", optionA: "必然性", optionB: "可能性", dimA: 'S', dimB: 'N' },
  { id: 46, text: "哪個詞更吸引你：", optionA: "訴諸情感", optionB: "訴諸理智", dimA: 'F', dimB: 'T' },
  { id: 47, text: "哪個詞更吸引你：", optionA: "健談", optionB: "內斂", dimA: 'E', dimB: 'I' },
  { id: 48, text: "哪個詞更吸引你：", optionA: "溫和", optionB: "力量", dimA: 'F', dimB: 'T' },
  { id: 49, text: "哪個詞更吸引你：", optionA: "現實", optionB: "理想", dimA: 'S', dimB: 'N' },
  { id: 50, text: "哪個詞更吸引你：", optionA: "心地善良", optionB: "能力出眾", dimA: 'F', dimB: 'T' },
  { id: 51, text: "哪個詞更吸引你：", optionA: "事實", optionB: "理論", dimA: 'S', dimB: 'N' },
  { id: 52, text: "哪個詞更吸引你：", optionA: "有系統", optionB: "隨性", dimA: 'J', dimB: 'P' },
  { id: 53, text: "哪個詞更吸引你：", optionA: "寫實", optionB: "想像", dimA: 'S', dimB: 'N' },
  { id: 54, text: "哪個詞更吸引你：", optionA: "情感", optionB: "客觀", dimA: 'F', dimB: 'T' },
  { id: 55, text: "哪個詞更吸引你：", optionA: "建造", optionB: "發明", dimA: 'S', dimB: 'N' },
  { id: 56, text: "哪個詞更吸引你：", optionA: "溫情", optionB: "務實", dimA: 'F', dimB: 'T' },
  { id: 57, text: "哪個詞更吸引你：", optionA: "井然有序", optionB: "隨意", dimA: 'J', dimB: 'P' },
  { id: 58, text: "哪個詞更吸引你：", optionA: "外向", optionB: "文靜", dimA: 'E', dimB: 'I' },
  { id: 59, text: "哪個詞更吸引你：", optionA: "認同", optionB: "分析", dimA: 'F', dimB: 'T' },
  { id: 60, text: "哪個詞更吸引你：", optionA: "事實", optionB: "想像", dimA: 'S', dimB: 'N' },
  { id: 61, text: "哪個詞更吸引你：", optionA: "祝福", optionB: "效益", dimA: 'F', dimB: 'T' },
  { id: 62, text: "哪個詞更吸引你：", optionA: "細節", optionB: "大綱", dimA: 'S', dimB: 'N' },
  { id: 63, text: "哪個詞更吸引你：", optionA: "果斷", optionB: "衝動", dimA: 'J', dimB: 'P' },
  { id: 64, text: "哪個詞更吸引你：", optionA: "製作", optionB: "創造", dimA: 'S', dimB: 'N' },
  { id: 65, text: "哪個詞更吸引你：", optionA: "溫暖", optionB: "客觀", dimA: 'F', dimB: 'T' },
  { id: 66, text: "哪個詞更吸引你：", optionA: "務實", optionB: "迷人", dimA: 'S', dimB: 'N' },
  { id: 67, text: "哪個詞更吸引你：", optionA: "體貼", optionB: "公平", dimA: 'F', dimB: 'T' },
  { id: 68, text: "哪個詞更吸引你：", optionA: "社交", optionB: "文靜", dimA: 'E', dimB: 'I' },
  { id: 69, text: "哪個詞更吸引你：", optionA: "細膩", optionB: "明理", dimA: 'F', dimB: 'T' },
  { id: 70, text: "哪個詞更吸引你：", optionA: "製造", optionB: "設計", dimA: 'S', dimB: 'N' },
  { id: 71, text: "哪個詞更吸引你：", optionA: "同理心", optionB: "邏輯", dimA: 'F', dimB: 'T' },
  { id: 72, text: "哪個詞更吸引你：", optionA: "公開", optionB: "私密", dimA: 'E', dimB: 'I' },
  { id: 73, text: "哪個詞更吸引你：", optionA: "慈悲", optionB: "遠見", dimA: 'F', dimB: 'T' },
  { id: 74, text: "你通常更喜歡：", optionA: "提前安排閒暇活動", optionB: "隨興而為，看心情決定", dimA: 'J', dimB: 'P' },
  { id: 75, text: "在人群中是否會：", optionA: "讓你感到精力充沛", optionB: "讓你感到精疲力竭", dimA: 'E', dimB: 'I' },
  { id: 76, text: "在大多數情況下，你更喜歡：", optionA: "遵循時間表", optionB: "順其自然", dimA: 'J', dimB: 'P' },
  { id: 77, text: "在派對上，你：", optionA: "總是玩得很開心", optionB: "有時會感到無聊", dimA: 'E', dimB: 'I' },
  { id: 78, text: "做決定時，對你來說更重要的是：", optionA: "考慮別人的感受和意見", optionB: "衡量事實情況", dimA: 'F', dimB: 'T' },
  { id: 79, text: "你喜歡：", optionA: "提前做好充分準備", optionB: "先看情況發展再做計畫", dimA: 'J', dimB: 'P' },
  { id: 80, text: "對別人來說：", optionA: "了解你很容易", optionB: "了解你很難", dimA: 'E', dimB: 'I' },
  { id: 81, text: "你更喜歡：", optionA: "堅持已經有效的方法", optionB: "分析尚未解決的問題並挑戰它", dimA: 'S', dimB: 'N' },
  { id: 82, text: "你覺得你更像是一個：", optionA: "有組織的人", optionB: "隨性的人", dimA: 'J', dimB: 'P' },
  { id: 83, text: "你能：", optionA: "只要願意，能與幾乎任何人滔滔不絕", optionB: "只能與志同道合的人長談", dimA: 'E', dimB: 'I' },
  { id: 84, text: "你寧願在什麼樣的主管手下工作：", optionA: "心地善良但標準不一", optionB: "嚴格但有條理", dimA: 'F', dimB: 'T' },
  { id: 85, text: "你喜歡根據什麼做大多數事情：", optionA: "固定的時間表", optionB: "當天的感覺", dimA: 'J', dimB: 'P' },
  { id: 86, text: "在派對上，你通常：", optionA: "說話比較多", optionB: "負責聽別人說話", dimA: 'E', dimB: 'I' },
  { id: 87, text: "通常你更喜歡涉及以下內容的課程：", optionA: "具體內容", optionB: "概念與準則", dimA: 'S', dimB: 'N' },
  { id: 88, text: "開始一項下一週就要交的大型計畫時，你會：", optionA: "花時間列出清單與順序", optionB: "直接開始動手做", dimA: 'J', dimB: 'P' },
  { id: 89, text: "在社交場合，你通常覺得：", optionA: "與大多數人長談很容易", optionB: "很難與某些人開始並維持長談", dimA: 'E', dimB: 'I' },
  { id: 90, text: "對你來說，哪個稱讚更高級：", optionA: "富有同情心", optionB: "具備競爭力", dimA: 'F', dimB: 'T' },
  { id: 91, text: "你覺得遵循計畫是：", optionA: "大多數時候都很有幫助且合適", optionB: "有時有必要，但令人厭煩", dimA: 'J', dimB: 'P' },
  { id: 92, text: "你通常：", optionA: "能很好地與他人打成一片", optionB: "傾向於保持安靜且獨處", dimA: 'E', dimB: 'I' },
  { id: 93, text: "總體來說，完成一項重大任務時，你傾向於：", optionA: "先確定每一個步驟", optionB: "一邊做一邊想接下來該做什麼", dimA: 'J', dimB: 'P' }
];

export const personalityDescriptions: Record<string, { title: string, desc: string }> = {
  "ISTJ": { title: "物流師 / 調查員", desc: "安靜、嚴肅，透過徹底和可靠獲得成功。務實、實事求是、現實且負責。能理智地決定該做什麼，並穩定地朝目標努力，不受干擾。喜歡讓工作、家庭和生活都井然有序且有組織。重視傳統和忠誠。" },
  "ISFJ": { title: "守護者 / 支援者", desc: "安靜、友好、負責且認真。致力於履行義務，穩定且持久。徹底、辛苦且準確。忠誠、體貼，能注意到並記住對他們重要的人的細節，關心他人的感受。努力在工作和家中創造一個有序且和諧的環境。" },
  "INFJ": { title: "提倡者 / 諮詢師", desc: "在想法、關係和物質享受中尋找意義和聯繫。想了解人們的動機，對他人有洞察力。認真且致力於自己的堅定價值觀。對如何最好地服務公共利益有清晰的願景。在實行願景時有組織且果斷。" },
  "INTJ": { title: "建築師 / 策略家", desc: "擁有獨創的思想和強大的動力來實行想法並達成目標。能迅速識破外部事件的模式，並建立長遠的解釋視角。一旦做出承諾，就會組織工作並貫徹到底。懷疑且獨立，對自己和他人的能力和表現都有很高的標準。" },
  "ISTP": { title: "鑒賞家 / 巧匠", desc: "寬容且靈活；安靜的觀察者直到問題出現，然後迅速行動尋找可行的解決方案。分析是什麼讓事情運作，並能輕易處理大量資料以隔離務實問題的核心。對因果感興趣，使用邏輯原則組織事實，重視效率。" },
  "ISFP": { title: "探險家 / 作曲家", desc: "安靜、友好、敏感且善良。享受當下，享受身邊發生的一切。喜歡有自己的空間，並在自己的時間框架內工作。對其價值觀和對他們重要的人保持忠誠。不喜歡爭執和衝突，不會強迫他人接受自己的意見或價值觀。" },
  "INFP": { title: "調解者 / 治癒者", desc: "理想主義，對其價值觀和對他們重要的人保持忠誠。希望外在生活與其價值觀一致。好奇，能迅速看到可能性，能成為實行想法的催化劑。尋求了解人們並幫助他們發揮潛力。適應力強、靈活且包容，除非價值觀受到威脅。" },
  "INTP": { title: "邏輯學家 / 建築師", desc: "尋求為感興趣的一切發展邏輯解釋。理論化且抽象，對想法比對社交更感興趣。安靜、內斂、靈活且適應力強。有不尋常的能力來深入專注於解決所感興趣領域的問題。懷疑、有時帶有批判性，總是充滿分析精神。" },
  "ESTP": { title: "企業家 / 推廣者", desc: "靈活且寬容，採取專注於即時結果的務實方法。理論性與抽象的解釋讓他們感到無聊——他們想積極行動來解決問題。專注於此時此刻，自發、享受能與他人一起活動的每一刻。享受物質舒適和風格。透過實踐學習效果最好。" },
  "ESFP": { title: "表演者", desc: "外向、友好且包容。熱愛生活、他人和物質舒適。享受與他人一起工作讓事情發生。將常識和務實的方法帶入工作，並讓工作變得有趣。靈活且自發，能輕易適應新的人、新的環境。透過與他人一起嘗試新技能學習效果最好。" },
  "ENFP": { title: "競選者 / 冠軍", desc: "熱情且富有想像力。認為生活充滿可能性。能迅速在事件與資訊之間建立聯繫，並根據所看到的模式自信地前行。希望得到他人的大量認可，並樂於給予賞識與支持。自發且靈活，通常依賴即興創作的能力和口才。" },
  "ENTP": { title: "辯論家 / 發明家", desc: "反應快、足智多謀、激發靈感、警覺且直言不諱。在解決新的、挑戰性的問題時資源豐富。擅長產生概念上的可能性並進行戰略分析。善於讀人。對例行公事感到無聊，很少以同樣的方式做同樣的事，傾向於轉向一個接一個的新興趣。" },
  "ESTJ": { title: "總經理 / 監督者", desc: "務實、現實、實事求是。果斷，迅速實行決定。組織計畫和人員以完成任務，專注於以最有效的方式獲得結果。處理日常細節。有一套清晰的邏輯標準，系統地遵循它們並希望他人也如此。在實行計畫時強而有力。" },
  "ESFJ": { title: "執政官 / 提供者", desc: "熱心、認真且合作。希望環境和諧，並決心建立和諧。喜歡與他人一起準確且準時地完成任務。忠誠，即使是小事也會贯彻到底。注意到他人在日常生活中的需求並努力提供。希望因他們是誰以及他們的貢獻而被賞識。" },
  "ENFJ": { title: "主人公 / 教師", desc: "溫暖、有同理心、反應靈敏且負責。高度關注他人的情感、需求和動機。在每個人身上發現潛力，想幫助他人發揮潛力。可作為個人和團體成長的催化劑。忠誠，對稱讚和批評都有反應。善於社交，在團體中促進他人，並提供鼓舞人心的領導。" },
  "ENTJ": { title: "指揮官", desc: "坦率、果斷，易於擔任領導角色。能迅速識破不合邏輯且效率低下的程序和政策，並發展和實施全面的系統來解決組織問題。享受長期規劃和目標設定。通常資訊豐富、博學，享受擴展知識並將其傳遞給他人。在陳述想法時強而有力。" }
};
